---
title: "Visualizing_ThermTol_Pheno_Data"
author: "Patricka Williams-Simon"
date: "3/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(cowplot)
library(dplyr)
library(ggrepel)
source(file="../../Functions/ggplot_theme.R")
```

#read or load in flies

```{r}
#make individual plots
rawdTT <- read.table("../ProcessedData/ThermalTol_processed.txt",sep="\t", header=TRUE, stringsAsFactors = FALSE)
str(rawdTT)

#make mean graphs
load(file="../ProcessedData/T_TDATA.rda")


#RILs that we used in RNAseq
RIL_rna <- data.frame("Pool"= rep(c('LH','LL','MH','ML','TH','TL'),each=7), 
                      "patRIL"= c(11065,12359,11146,11144,11006,11122,11023,
                                  12044,12285,12138,12022,11189,12084,12324,
                                  12018,12039,12074,11184,12071,11122,11023,
                                  12383,12030,12285,11189,11038,11133,11186,
                                  
                                  
                                  
                                  
                                
