---
title: "Ronel_ex"
author: "EGK"
date: "4/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(survival)
library(tidyverse)
library(forcats)
library(cowplot)
library(nlme)

font_size <- 20
my_theme <- theme(
  axis.text = element_text(size = font_size),
  axis.title = element_text(size = font_size),
  legend.text = element_text(size = font_size),
  legend.title=element_text(size = font_size),
  plot.title = element_text(size = font_size + 1))

```

## Get survivorship curves

```{r}

ttpheno43 <-read.csv("../Rawdata/NEW_Thermpheno.csv", stringsAsFactors = FALSE)

str(ttpheno43)

survplot_byRIL <- survfit(Surv(IncapTime) ~ Genotype, data= ttpheno43)

str(survplot_byRIL)

ids_n <- survplot_byRIL$strata

ids <- unlist(lapply(strsplit(names(ids_n), split="=", fixed=TRUE), function(x) x[2]))
class.id <- unique(ttpheno43[,c('Genotype','Class')], MARGIN=1)
class.id <- class.id[match(ids, as.character(class.id$Genotype)),]
  
datplot <- data.frame("RIL" = rep(ids, times=ids_n), "Class" = rep(class.id$Class, times=ids_n), "Proportion" = survplot_byRIL$surv, "Time"= survplot_byRIL$time, stringsAsFactors=FALSE)

survplot_byClass <- survfit(Surv(IncapTime) ~ Class, data= ttpheno43)
ids_n <- survplot_byClass$strata
classplot <- data.frame("Class" = rep(c("HIGH","MIDDLE"), times=ids_n), "Proportion" = survplot_byClass$surv, "Time"= survplot_byClass$time,  stringsAsFactors=FALSE)


ggplot(datplot, aes(x=Time, y=Proportion, group=RIL, color=Class)) +
  geom_line(size=0.8, alpha=1/2) +
  geom_hline(yintercept = 0.5, lty=3) +
  geom_line(data=classplot, aes(x=Time, y=Proportion, linetype=Class, color=Class), inherit.aes = FALSE, size=1.5)


```

## Mixed model

```{r}

mod <- lme(IncapTime~Sex*Class, random = ~ 1 | Genotype, data=ttpheno43)
summary(mod)



```

Sex is close to marginally significant. Class is not significant (sample size issue + one high line is not so high). Interaction is significant. What does your interaction plot look like?






