---
title: "h2_rg"
author: "EGK & PW-S"
date: "1/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(nlme)
library(tidyverse)
source("../../Functions/h2_functs.R")

```


## Phenotypic data

```{r}

rawdTT <- read.table("../../LearnMemTolPheno/ProcessedData/ThermalTol_processed.txt",sep="\t", header=TRUE, stringsAsFactors = FALSE)
str(rawdTT)

rawdLM <- rawdLM[,c('patRIL','Learning','Memory')]
rawdLM <- rawdLM %>% mutate(LearnNorm = quant.norm(Learning),
                            MemoryNorm = quant.norm(Memory))

rawdTT <- rawdTT[,c('patRIL','incapacitation')]
rawdTT <- rawdTT %>% mutate(ThermTolNorm = quant.norm(incapacitation))

```

## Broad sense heritability


```{r}

TT.h2 <- h2.lme(geno=as.factor(rawdTT$patRIL), pheno=rawdTT$ThermTolNorm)

geno <- as.factor(rawdTT$patRIL)
pheno <- rawdTT$ThermTolNorm

afit<-lme(pheno ~ 1 , random= ~1 | geno, method="ML")
afit.n <- lm(pheno ~ 1)
anova.lme(afit.n, afit)

#check
x2val <- -2*logLik(afit.n, REML=FALSE) + 2* logLik(afit, REML=FALSE)
pchisq(x2val, df=1, lower.tail=F, log.p = TRUE)


TT.jk <- jk.h2.lme(geno=as.factor(rawdTT$patRIL), pheno=rawdTT$ThermTolNorm)
mean(TT.jk, na.rm=TRUE)
sd(TT.jk, na.rm=TRUE)
nn <- length(TT.jk[is.na(TT.jk)==FALSE])
tval <- qt(0.025, nn-1, lower.tail=FALSE)
mean(TT.jk, na.rm=TRUE) + tval*sd(TT.jk, na.rm=TRUE)/sqrt(nn)
mean(TT.jk, na.rm=TRUE) - tval*sd(TT.jk, na.rm=TRUE)/sqrt(nn)


```

## Genetic correlation

```{r}

phen.l <- rawdLM[,c('patRIL','LearnNorm','MemoryNorm')] %>% gather(phenotype,value,-patRIL)

rg.lme(phenoval=phen.l$value, phenotype=phen.l$phenotype, geno=phen.l$patRIL)

psrg <- jk.rg.lme(phenoval=phen.l$value, phenotype=phen.l$phenotype, geno=phen.l$patRIL)

mean(psrg,na.rm=TRUE)
nn <- length(psrg[is.na(psrg)==FALSE])
tval <- qt(0.025, nn-1, lower.tail=FALSE)
mean(psrg, na.rm=TRUE) + tval*sd(psrg, na.rm=TRUE)/sqrt(nn)
mean(psrg, na.rm=TRUE) - tval*sd(psrg, na.rm=TRUE)/sqrt(nn)

length(psrg[is.na(psrg)])

#Thermal Tolerance

##note to self: you will have to merge the two df to be able to do the following steps

phen.t <- rawdTT[,c('patRIL','ThermTolNorm','LearnNorm')] %>% gather(phenotype,value,-patRIL)

rg.lme(phenoval=phen.t$value, phenotype=phen.t$phenotype, geno=phen.t$patRIL)

which(is.na(phen.t$phenotype))
which(is.na(phen.t$value))
which(is.na(phen.t$patRIL))

psrg <- jk.rg.lme(phenoval=phen.t$value, phenotype=phen.t$phenotype, geno=phen.t$patRIL)

mean(psrg,na.rm=TRUE)
nn <- length(psrg[is.na(psrg)==FALSE])
tval <- qt(0.025, nn-1, lower.tail=FALSE)
mean(psrg, na.rm=TRUE) + tval*sd(psrg, na.rm=TRUE)/sqrt(nn)
mean(psrg, na.rm=TRUE) - tval*sd(psrg, na.rm=TRUE)/sqrt(nn)

length(psrg[is.na(psrg)])
```


