---
title: "AlleleSp_lines_choose"
author: "Libby King"
date: "8/16/2020"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(DSPRqtlDataA)
library(tidyverse)
library(cowplot)
theme_set(theme_cowplot())

set.seed(108155)


```

# Identify lines for Allele Specific Expression Project

Goal is to find lines that are in the high & low haplotype group for thermal tolerance at our focal peak

### Get data

```{r}

load(file="../../LearnMemTolPheno/ProcessedData/T_TDATA.rda")

load(file ="../ProcessedData/Peaks_wCIs.rda")

tt.peaks <- ci.peak[["Tolsqrtvariable"]]

tt.foc <- tt.peaks[which.max(tt.peaks$LL),]

tt.foc

```

### Get haplotype id for each RIL

```{r}

#haplotype data at a given position
objname<-paste("A_",tt.foc$chr,"_",tt.foc$Ppos,sep="")
data(list=objname)
geno <- get(objname)
geno <- geno[,c("ril", "AA1","AA2","AA3","AA4","AA5","AA6","AA7","AA8")]

geno$ril <- as.integer(geno$ril)

geno$hard <- paste0("A",apply(geno[,2:9], 1, which.max))
geno$hprob <- apply(geno[,2:9], 1, max)
  
T_all <- merge(T_TDATA, geno[,c('ril','hard','hprob')], by.x="patRIL",by.y='ril')

```

### Choose lines

```{r}

#check means per group outside of model fit

sum.dat <- T_all %>% 
  group_by(hard) %>%
  summarise(meanraw= mean(Incapacitation_Mean),meantrans= mean(Tolsqrtvariable))

#A5 high, A4 low
rr.list <- T_all[c(sample(which(T_all$hard=="A4" & T_all$hprob>0.95),25, replace=FALSE), sample(which(T_all$hard=="A5" & T_all$hprob>0.95),25, replace=FALSE)),]

rr.list[which(rr.list$patRIL %in% c(11480, 12049,12069, 12093, 12116)),]

T_all.minus <- T_all[which(!(T_all$patRIL %in% rr.list$patRIL)),]

#possible replacements
rr.list.rep <- T_all.minus[c(sample(which(T_all.minus$hard=="A4" & T_all.minus$hprob>0.95),10, replace=FALSE), sample(which(T_all.minus$hard=="A5" & T_all.minus$hprob>0.95),10, replace=FALSE)),]


#checks
which(duplicated(rr.list$patRIL))
min(rr.list$hprob)
rr.list %>% 
  group_by(hard) %>%
  summarise(meanraw= mean(Incapacitation_Mean),meantrans= mean(Tolsqrtvariable))

#plot raw data

p1 <- ggplot(T_all, aes(hard, Incapacitation_Mean, color=hard)) +
  geom_point(position = position_jitter(width = 0.4), alpha = 1/4) +
  stat_summary(fun = mean, geom = "point", pch = 12, size = 5) +
  geom_point(data = rr.list, aes(hard, Incapacitation_Mean), color="black",position = position_jitter(width = 0.4), alpha = 1/2)

p1

#write.table(sort(rr.list[,"patRIL"]),file= #"../ProcessedData/HL_thermQTL_lines.txt", row.names=FALSE)




```


## Look at which SJM actually sent

```{r}

rr.all <- rbind(rr.list, rr.list.rep)

rcd.list <- read.table(file="../ProcessedData/HL_thermQTL_lines_recvd.txt", header=TRUE)

ww <- which(rr.all$patRIL %in% rcd.list$patRIL)

rr.rcd <- rr.all[ww,]

rr.rcd.a4 <- subset(rr.rcd, hard == "A4")
rr.rcd.a4 <- rr.rcd.a4[order(rr.rcd.a4$Incapacitation_Mean),]


rr.rcd.a5 <- subset(rr.rcd, hard == "A5")
rr.rcd.a5 <- rr.rcd.a5[order(-rr.rcd.a5$Incapacitation_Mean),]

ase.set <- rbind(rr.rcd.a4[sample(seq(1:12)),],rr.rcd.a5[sample(seq(1:12)),])

ase.set$type <- rep("H",nrow(ase.set))
ase.set$type[ase.set$hard=="A4"] <- "L"
ase.set$sort <- c(seq(from=1,to=23,by=2),seq(from=2,to=24, by=2))
ase.set <- ase.set[order(ase.set$sort),]

#write.table(ase.set, #file="../ProcessedData/HL_thermQTL_lines_testset.txt", sep="\t", #row.names=FALSE)

```
