---
title: "Individual_peak"
author: "EGK & PW-S"
date: "10/28/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(DSPRqtl)
library(ggplot2)
library(cowplot)
library(tidyverse)
library(gridExtra)


#conversion table
load(file = "../ProcessedData/DSPR_5_6_parsed.rda")
coord.table$R5pos<-as.numeric(coord.table$R5pos)
coord.table$R6pos<-as.numeric(coord.table$R6pos)

source("../../Functions/mappingfunctions.R")
source("../../Functions/ggplot_theme.R")


```

# Make individual peak plots
  - Get set of peaks
  - Get genes under peaks (all?)
  - highlight DE genes


## Load data
```{r}
#phenotype data
load(file="../../LearnMemTolQTL/ProcessedData/myGenos.rda")
Nrils <- nrow(myGenos$phenotype)
rm(myGenos)

#LOD scores 
load(file="../../LearnMemTolQTL/ProcessedData/Lodscores_3traits.rda")

#Peak data
load(file ="../../LearnMemTolQTL/ProcessedData/Peaks_wCIs.rda")

#DE genes
load(file="../../LearnMemTolQTL/ProcessedData/Learn_genes_under_peak.rda")
load(file="../../LearnMemTolQTL/ProcessedData/Mem_genes_under_peak.rda")

#convert LOD data to long format
#convert 5-6
#convert LOD to p-value
obs.LM_long <-gather(obs.LL, key='Trait', value='LOD', LearnPowerTrans, Memory_Mean)

obs.LM_long <- merge(obs.LM_long, coord.table, by.x=c('chr','Ppos'), by.y=c('R5chr','R5pos'),sort=FALSE)

obs.LM_long$pval <- getP(obs.LM_long$LOD,Nrils,7,Nrils-8)
obs.LM_long$R6pos <- as.numeric(obs.LM_long$R6pos)

lapply(learn.list, nrow)
lapply(Mem.list, nrow)

```

## Make ind plot

```{r}
fdr<-5.5
fwer<-7.3

pfdr <- getP(fdr,Nrils,7,Nrils-8)
pfwer <- getP(fwer,Nrils,7,Nrils-8)

#only do peaks with DEG in them
pad.pos <- 2

foc.peak <- ci.peak[[1]][5,]

  

set <- subset(obs.LM_long, chr==foc.peak$chr & 
                Gpos < (foc.peak$Gpos + pad.pos) &
                Gpos > (foc.peak$Gpos - pad.pos))

line.ww <- 0.5

if(max(set$pval) > pfwer)
{
  top <- max(set$pval)
}else{
  top <- pfwer
}

#peak.plot <- vector(mode="list", length=)

p1 <- ggplot(set, aes(x=R6pos/1e6, y=pval, color=Trait)) +
    geom_line(alpha=0.8, size=line.ww) +
  
  geom_segment(x= -10, xend=30,y=pfwer,yend=pfwer, color='black', size=line.ww) +
  geom_segment(x=-10, xend=30,y=pfdr,yend=pfdr, color='black', size=line.ww, lty=3) +
  ylim(c(0,top)) +
  ylab("Pval")+
  xlab("Position (Mbp)") +
  theme(legend.position = "none") +
  my_theme
p1
#ggsave(p1, file="../Plots/indpeak.pdf",width=4, height=2)




#scale_color_discrete(name='Phenotype',breaks=c('LearnPowerTrans','Memory_Mean'), labels=c('Learning','Memory'))
```

##Gene summaries 


```{r}

#load fly base summary
gsum <- read_lines(file = "../ProcessedData/automated_gene_summaries.tsv.gz",
                   skip = 1)%>%
  str_split(pattern = "\t", simplify = TRUE) %>% 
  as_tibble() 
gsum <- gsum[,c(1,2)]
colnames(gsum) <- c('FBgn', 'summary')


#load gene list (file list is created in Identify_peaks.R script)
learn.list
Mem.list

#to view a specific column
result = lapply(learn.list, "[", , c("gname"))

#to find the summary for all the genes under a single peak

#learning
Learnfocal.peak1 <- learn.list[[1]]
Learnfocal.peak2 <- learn.list[[2]]
Learnfocal.peak3 <- learn.list[[3]]
Learnfocal.peak4 <- learn.list[[4]]
Learnfocal.peak5 <- learn.list[[5]]
Learnfocal.peak6 <- learn.list[[6]]
Learnfocal.peak7 <- learn.list[[7]]
Learnfocal.peak9 <- learn.list[[9]]
Learnfocal.peak10 <- learn.list[[10]]
Learnfocal.peak11 <- learn.list[[11]]
Learnfocal.peak12 <- learn.list[[12]]
Learnfocal.peak13 <- learn.list[[13]]
Learnfocal.peak14 <- learn.list[[14]]

lff1 <- merge(Learnfocal.peak1, gsum, by='FBgn')
lff2 <- merge(Learnfocal.peak2, gsum, by='FBgn')
lff3 <- merge(Learnfocal.peak3, gsum, by='FBgn')
lff4 <- merge(Learnfocal.peak4, gsum, by='FBgn')
lff5 <- merge(Learnfocal.peak5, gsum, by='FBgn')
lff6 <- merge(Learnfocal.peak6, gsum, by='FBgn')
lff7 <- merge(Learnfocal.peak7, gsum, by='FBgn')
lff9 <- merge(Learnfocal.peak9, gsum, by='FBgn')
lff10 <- merge(Learnfocal.peak10, gsum, by='FBgn')
lff11 <- merge(Learnfocal.peak11, gsum, by='FBgn')
lff12 <- merge(Learnfocal.peak12, gsum, by='FBgn')
lff13 <- merge(Learnfocal.peak13, gsum, by='FBgn')
lff14 <- merge(Learnfocal.peak14, gsum, by='FBgn')

#to view
lff1[1,]

length(lff12)

#memory 
Memfocal.peak3 <- Mem.list[[3]]
Memfocal.peak4 <- Mem.list[[4]]
Memfocal.peak5 <- Mem.list[[5]]
Memfocal.peak7 <- Mem.list[[7]]

mff3 <- merge(Memfocal.peak3, gsum, by='FBgn')
mff4 <- merge(Memfocal.peak4, gsum, by='FBgn')
mff5 <- merge(Memfocal.peak5, gsum, by='FBgn')
mff7 <- merge(Memfocal.peak7, gsum, by='FBgn')

mff7[1,]


#to look at specific genes 
dpr20 <- grep("dpr20", gsum$summary)
gsum[dpr20[1],'summary']
pull(gsum[dpr20[1],'summary'])

CG9119 <- grep("CG9119", gsum$summary)
gsum[CG9119[1],'summary']
pull(gsum[CG9119[1],'summary'])

mwh <- grep("mwh", gsum$summary)
gsum[mwh[1],'summary']
pull(gsum[mwh[1],'summary'])

```



