---
title: "TT-founder-effect-Q6"
author: "Patricka Williams-Simon"
date: "9/10/2020"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(DSPRqtlDataA)
library(tidyverse)
library(ggplot2)
library(cowplot)
theme_set(theme_cowplot())

set.seed(108155)
```
# Identify founders at Q6 

Goal is to identify the founders effect at Q6 for thermal tolerance. This data will be used to identify which RILs have low or high haplotype at Q6.


### Get data


```{r}

load(file="../../LearnMemTolPheno/ProcessedData/T_TDATA.rda")

load(file ="../ProcessedData/Peaks_wCIs.rda")

tt.peaks <- ci.peak[["Tolsqrtvariable"]]

tt.foc <- tt.peaks[which.max(tt.peaks$LL),]

tt.foc


```

### Get haplotype id for each RIL



```{r}
#haplotype data at a given position
objname<-paste("A_",tt.foc$chr,"_",tt.foc$Ppos,sep="")
data(list=objname)
geno <- get(objname)
geno <- geno[,c("ril", "AA1","AA2","AA3","AA4","AA5","AA6","AA7","AA8")]

geno$ril <- as.integer(geno$ril)

geno$hard <- paste0("A",apply(geno[,2:9], 1, which.max))
geno$hprob <- apply(geno[,2:9], 1, max)
  
T_all <- merge(T_TDATA, geno[,c('ril','hard','hprob')], by.x="patRIL",by.y='ril')



```

### make plot to visualize hplotype means at Q6

```{r}

p1 <- ggplot(T_all, aes(hard, Incapacitation_Mean, color=hard)) +
  geom_point(position = position_jitter(width = 0.4), alpha = 1/4) +
  stat_summary(fun = mean, geom = "point", pch = 12, size = 5)

```

```
