---
title: "Individual_peak"
author: "EGK & PW-S"
date: "10/28/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(DSPRqtl)
library(tidyverse)
library(gridExtra)

```


## Load data
```{r}

#Peak data
load(file ="../../LearnMemTolQTL/ProcessedData/Peaks_wCIs.rda")

```


##Gene summaries 


```{r}

#load fly base summary
gsum <- read_lines(file = "../ProcessedData/automated_gene_summaries.tsv.gz",
                   skip = 1)%>%
  str_split(pattern = "\t", simplify = TRUE) %>% 
  as_tibble() 
gsum <- gsum[,c(1,2)]
colnames(gsum) <- c('FBgn', 'summary')


#load gene list (file list is created in Identify_peaks.R script)
learn.list
Mem.list

#to view a specific column
result1 = lapply(learn.list, "[", , c("gname"))
result2 = lapply(Mem.list, "[" , c("gname"))


#to find the summary for all the genes under a single peak

#learning
Learnfocal.peak1 <- learn.list[[1]]
Learnfocal.peak2 <- learn.list[[2]]
Learnfocal.peak3 <- learn.list[[3]]
Learnfocal.peak4 <- learn.list[[4]]
Learnfocal.peak5 <- learn.list[[5]]
Learnfocal.peak6 <- learn.list[[6]]
Learnfocal.peak7 <- learn.list[[7]]
Learnfocal.peak9 <- learn.list[[9]]
Learnfocal.peak10 <- learn.list[[10]]
Learnfocal.peak11 <- learn.list[[11]]
Learnfocal.peak12 <- learn.list[[12]]
Learnfocal.peak13 <- learn.list[[13]]
Learnfocal.peak14 <- learn.list[[14]]

lff1 <- merge(Learnfocal.peak1, gsum, by='FBgn')
lff2 <- merge(Learnfocal.peak2, gsum, by='FBgn')
lff3 <- merge(Learnfocal.peak3, gsum, by='FBgn')
lff4 <- merge(Learnfocal.peak4, gsum, by='FBgn')
lff5 <- merge(Learnfocal.peak5, gsum, by='FBgn')
lff6 <- merge(Learnfocal.peak6, gsum, by='FBgn')
lff7 <- merge(Learnfocal.peak7, gsum, by='FBgn')
lff9 <- merge(Learnfocal.peak9, gsum, by='FBgn')
lff10 <- merge(Learnfocal.peak10, gsum, by='FBgn')
lff11 <- merge(Learnfocal.peak11, gsum, by='FBgn')
lff12 <- merge(Learnfocal.peak12, gsum, by='FBgn')
lff13 <- merge(Learnfocal.peak13, gsum, by='FBgn')
lff14 <- merge(Learnfocal.peak14, gsum, by='FBgn')

#to view
lff1[1,]

length(lff12)

#memory 
Memfocal.peak3 <- Mem.list[[3]]
Memfocal.peak4 <- Mem.list[[4]]
Memfocal.peak5 <- Mem.list[[5]]
Memfocal.peak7 <- Mem.list[[7]]

mff3 <- merge(Memfocal.peak3, gsum, by='FBgn')
mff4 <- merge(Memfocal.peak4, gsum, by='FBgn')
mff5 <- merge(Memfocal.peak5, gsum, by='FBgn')
mff7 <- merge(Memfocal.peak7, gsum, by='FBgn')

mff7[1,]


#to look at specific genes 
dpr20 <- grep("dpr20", gsum$summary)
gsum[dpr20[1],'summary']
pull(gsum[dpr20[1],'summary'])

CG9119 <- grep("CG9119", gsum$summary)
gsum[CG9119[1],'summary']
pull(gsum[CG9119[1],'summary'])

mwh <- grep("mwh", gsum$summary)
gsum[mwh[1],'summary']
pull(gsum[mwh[1],'summary'])

```



