---
title: "Processing_TTPheno_Founders"
author: "Patricka Williams-Simon"
date: "2/26/2020"
output: html_document
---

```{r setup, include=FALSE}
library(readxl)
library(ggplot2)
library(DSPRqtl)
library(DSPRqtlDataA)
library(tidyverse)

theme_set(theme_cowplot())

source(file="../../Functions/ggplot_theme.R")
```

## Read in ThermTol Founders raw data and check
```{r}
load(file="../Processed_Data/Incapacitation_Founder.rda")

str(ThermTol)
ThermTol[1:5,]
nchar(ThermTol)


```


## Find means, SEMs and percentiles for trait

```{r}
#find the range 
subset(ThermTol, p==3)

ThermTol$Range = max(ThermTol, patRIL=A1_Incapacitation) - min(ThermTol$incapacitation)

#find the range for each founder
ThermTol<- subset(ThermTol$incapacitation== A1_Incapacitation, 'patRIL')

#calculate mean and SEM for incapacitation 
TTFoundDATA <- ThermTol %>% 
  group_by(patRIL) %>% 
  summarise(Incapacitation_Mean = mean(incapacitation),
            Incapacitation_SEM = sd(incapacitation)/sqrt(length(incapacitation)),
            N = length(incapacitation))


#find percentile
TTFoundDATA$Percentile<- ecdf(TTFoundDATA$Incapacitation_Mean)(TTFoundDATA$Incapacitation_Mean)



TTFoundDATA$Range = max(ThermTol$incapacitation, na.rm=TRUE) - min(ThermTol$incapacitation, na.rm=TRUE)

```


## sort through data
```{r}

#length of string
nchar(ThermTol)

#to get range
ThermTol[which.min(ThermTol$incapacitation),]
ThermTol[which.max(ThermTol$incapacitation),]


#
ThermTol[ThermTol$patRIL==A6_Incapacitation,'incapacitation']


summ <- data.frame(min=apply(scores[,!grepl("patRIL",colnames(scores))],2,min),
                   max=apply(scores[,!grepl("patRIL",colnames(scores))],2,max))

#look at a specific Founder
ThermTol[ThermTol$patRIL==A1_Incapacitation,'Incapacitation_Mean']




```

## Visualize data

```{r}
#Make histogram LearnMem
TTFoundhisto <- ggplot(TTFoundDATA, aes(x = Incapacitation_Mean)) +
  geom_histogram()

#View graph
TTFoundhisto

```


## Check dataset

```{r}

#look at dataset 
TTFoundDATA

#Identify minimum mean (find really low learning point identified in histograms)
TTFoundDATA[which.min(TTFoundDATA$Incapacitation_Mean),]



#Sort and save from decreasing to increasing means 
TTFoundDATA_sort <- TTFoundDATA[order(TTFoundDATA$Incapacitation_Mean),]


#change patRIL names first 
ThermTol$patRIL <- sub("[_]", "", ThermTol$patRIL)

#visualize data set

TT_Founders_pheno <- ggplot(ThermTol, aes(patRIL, incapacitation, color=patRIL)) +
  geom_point(position = position_jitter(width = 0.4), alpha = 1/4) +
  stat_summary(fun = mean, geom = "point", pch = 12, size = 5) + 
stat_summary(fun.data = mean_se, 
               geom = "errorbar", 
               color = 'black', width=.3, size=0.5, alpha=1/2 ) +
  guides(col=guide_legend("Founder Mean")) +
  ylab("Incapacitation Mean") +
 xlab("Founders") +
  my_theme
  

TT_Founders_pheno

ggsave(TT_Founders_pheno,file="../Plots/TT_Founders_pheno.pdf", width=10, height=10)



```



##Transform data set (only if necessary). There are several methods used to transform data, choose the best fit.

```{r}

#log transformation, log10 transformation, arcsign transformation 

#sqaure root transformation
T_TDATA$Tolsqrtvariable<-sqrt(T_TDATA$Incapacitation_Mean)

#after transformation always visualize data
ggplot(T_TDATA, aes(x = T_TDATA$Tolsqrtvariable)) +
  geom_histogram()

#save new dataset
save(T_TDATA, file="../ProcessedData/T_TDATA.rda")

```

