---
title: "Prep DESeq-worthy counts from StringTie output"
author: "Patricka Williams-Simon"
date: "7/19/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(DESeq2)
library(dplyr)
library(stringr)
library(sva)
library(ggplot2)
```

# Load gene(/transcript) count matrix and labels

```{r}

# Read in data frame and fill in empty spaces in column 2 with value in 1
TTgenes <- read.csv("../Data/ThermTolBallgown/ballgown_eb/TTgene_count_matrix_eb.csv", stringsAsFactors = FALSE)


#delete first 3 row name, so that data set macthes up with pheno data.
rownames(TTgenes) <- TTgenes[,1]
TTgenes[,1] <- NULL


TTgenes <- as.matrix(TTgenes)


#load phenotype data

PhenoData <- read.csv("../Data/sample_description.csv", stringsAsFactors = FALSE)


#Separate traits into different obejects and add id column 

TTpheno <- PhenoData %>% filter(treatment %in% c("TH", "TH_Incu", "TH_Incu_control", "TL","TL_Incu", "TL_Incu_control"  ))

names(TTpheno)[1]<-"ids"
TTpheno <- TTpheno %>%
  select(ids,treatment,replicate)

rownames(TTpheno) <- TTpheno[,1]
TTpheno[,1] <- NULL

#Add pool, condition an batch column
TTpheno$pool <- TTpheno$treatment
TTpheno$condition <- TTpheno$treatment
TTpheno$batch <- TTpheno$treatment


#assign variables o new columns
TTpheno$pool[TTpheno$treatment=='TL'] <- "L"
TTpheno$pool[TTpheno$treatment=='TL_Incu'] <- "L"
TTpheno$pool[TTpheno$treatment=='TL_Incu_control'] <- "L"
TTpheno$pool[TTpheno$treatment=='TH'] <- "H"
TTpheno$pool[TTpheno$treatment=='TH_Incu'] <- "H"
TTpheno$pool[TTpheno$treatment=='TH_Incu_control'] <- "H"

TTpheno$condition[TTpheno$treatment=='TL'] <- "RT"
TTpheno$condition[TTpheno$treatment=='TL_Incu'] <- "Incu"
TTpheno$condition[TTpheno$treatment=='TL_Incu_control'] <- "RT"
TTpheno$condition[TTpheno$treatment=='TH'] <- "RT"
TTpheno$condition[TTpheno$treatment=='TH_Incu'] <- "Incu"
TTpheno$condition[TTpheno$treatment=='TH_Incu_control'] <- "RT"

TTpheno$batch[TTpheno$treatment=='TL'] <- "A"
TTpheno$batch[TTpheno$treatment=='TL_Incu'] <- "B"
TTpheno$batch[TTpheno$treatment=='TL_Incu_control'] <- "B"
TTpheno$batch[TTpheno$treatment=='TH'] <- "A"
TTpheno$batch[TTpheno$treatment=='TH_Incu'] <- "B"
TTpheno$batch[TTpheno$treatment=='TH_Incu_control'] <- "B"



#order thermtol dataset 

TTpheno <- TTpheno[order (row.names(TTpheno)),]


# Check all sample IDs in colData are also in genecount and match their orders

all(rownames(TTpheno) %in% colnames(TTgenes))
genecount2 <- TTgenes[, rownames(TTpheno)]
all(rownames(TTpheno) == colnames(TTgenes))


#colData <- pData(phenDat)[,c("treatment","tissue")]
TTpheno <- as.matrix(TTpheno)

save(TTpheno, file="../Data/ThermRNAproc_data.rda")

```

# Control for batch effects

```{r}
TTdds <- DESeqDataSetFromMatrix(countData = TTgenes,
                              colData = TTpheno, 
                              design = ~batch + pool + condition)


TTdds_sva <- estimateSizeFactors(TTdds)
TTdat_sva <- counts(TTdds_sva, normalized=TRUE)
TTcc_c <- rowSums(TTdat_sva)

#remove all genes with 0s for all samples
TTdat_sva <- TTdat_sva[which(TTcc_c>0),]


TTpheno <- as.data.frame(TTpheno)

#fit model
TTmod <- model.matrix(~ as.factor(batch) + 
                        as.factor(pool) +
                        as.factor(condition), 
                         data=TTpheno)
#intercept
TTmod0 <- model.matrix(~ as.factor(batch), data=TTpheno) 


# calculate number of surrogate variables

TTn_sv <- num.sv(TTdat_sva, TTmod)

print(c("Calculated number of significant SVs = ", TTn_sv))

TTsv_obj <- svaseq(TTdat_sva, TTmod, TTmod0, n.sv=TTn_sv) 

#add SVs to phenotype dataset
TTpheno$SV1 <- TTsv_obj$sv[,1]
TTpheno$SV2 <- TTsv_obj$sv[,2]


head(TTdat_sva, 3)

TTdat_sva <- as.data.frame(TTdat_sva)

ggplot(TTpheno, aes(x=SV1, y=SV2)) +
geom_point(alpha=1/5, size=3)


# countData colnames() must be identical to colData rownames()
all(rownames(TTpheno) %in% colnames(TTgenes))
countdata <- TTgenes[, rownames(TTpheno)]
all(rownames(TTpheno) == colnames(TTgenes))
TTpheno$pool_con<- paste(TTpheno$pool,"_",TTpheno$condition, sep="")
TTpheno$pool_con <- as.factor(TTpheno$pool_con)

```

#Model with surrogate variables, batch, pool, and condition

```{r}
# DESeqDataSet for all variables,

#TT_dds_02 <- DESeqDataSetFromMatrix(countData = TTgenes, 
                                 #  colData = TTpheno, 
                                # design = ~ SV1 + SV2 + batch + pool*condition)

#TTlrt_inter_deseq <- DESeq(TT_dds_02, test="LRT", reduced=~ SV1 + SV2 + batch + pool + condition)
#TT_inter <- results(TTlrt_inter_deseq)
#save(TT_inter, file = "../Data/TTlrt_inter_deseq.Rda")

TT_dds_01 <- DESeqDataSetFromMatrix(countData = TTgenes, 
                                   colData = TTpheno, 
                                   design = ~ SV1 + SV2 + batch + pool + condition)


TTlrt_con_deseq <- DESeq(TT_dds_01, test="LRT", reduced=~ SV1 + SV2 + batch + pool)
TTlrt_con <- results(TTlrt_con_deseq)
save(TTlrt_con, file = "../Data/TTlrt_condiiton.Rda")


TTlrt_pool_deseq <- DESeq(TT_dds_01, test="LRT", reduced=~ SV1 + SV2 + batch + condition)
TTlrt_pool <- results(TTlrt_pool_deseq)
save(TTlrt_pool, file = "../Data/TTlrt_pool.Rda")



TT_dds_All <- DESeqDataSetFromMatrix(countData = TTgenes, 
                                   colData = TTpheno, 
                                   design = ~ SV1 + SV2 + batch + pool_con)

#DESeq step-by-step
TTlrt_All_deseq <- estimateSizeFactors(TT_dds_All)
nc <- counts(TTlrt_All_deseq , normalized=TRUE)
filter <- rowSums(nc >= 10) >= 2
TTlrt_All_deseq  <- estimateDispersions(TTlrt_All_deseq, fitType = "local")
TTlrt_All_deseq  <- nbinomWaldTest(TTlrt_All_deseq , maxit = 1000, useOptim = TRUE)
TTlrt_All_deseq  <- results(TTlrt_All_deseq )
save(TTlrt_All_deseq , file = "../Data/TTlrt_All.Rda")


#fold change for pool and condition
FCcon <- lfcShrink(TTlrt_con_deseq, contrast =c("condition", "Incu","RT" ), type="normal")
FCpool <- lfcShrink(TTlrt_pool_deseq, contrast =c("pool", "H","L" ), type="normal")


#fold change for each pair of combinations
pool <- c('H','L')
condition <- c('Incu','RT')

for (cc in condition)
{
  FC_THTL <- lfcShrink(TTlrt_pool_deseq, contrast=c("pool",paste("H_",cc,sep=""),paste("L_",cc,sep="")), type="normal")
 
  colnames(FC_THTL) <- c('baseMean',
                      paste("FC_H_",cc,sep=""),
                      paste("FCse_H_",cc,sep=""),
                      paste("stat_H_",cc,sep=""),
                      paste("p_H_",cc,sep=""),
                      paste("padj_H_",cc,sep=""))

}

#enoch
organs <- c('B','H','O')
treats <- c('DR','C','HS')

for(oo in organs)
{

FC_DRC <- lfcShrink(dds, contrast=c("treat_tissue",paste("DR_",oo,sep=""),paste("C_",oo,sep="")), type="normal")

FC_HSC <- lfcShrink(dds, contrast=c("treat_tissue",paste("HS_",oo,sep=""),paste("C_",oo,sep="")), type="normal")
  
FC_DRHS <- lfcShrink(dds, contrast=c("treat_tissue",paste("DR_",oo,sep=""),paste("HS_",oo,sep="")), type="normal")


#H_Incu vs L_Incu
#H_RT vs L_RT
#H_Incu vs H_RT
#L_Incu vs L_RT

colnames(FC_DRC) <- c('baseMean',
                      paste("FC_DR_",oo,sep=""),
                      paste("FCse_DR_",oo,sep=""),
                      paste("stat_DR_",oo,sep=""),
                      paste("p_DR_",oo,sep=""),
                      paste("padj_DR_",oo,sep=""))

colnames(FC_HSC) <- c('baseMean',
                      paste("FC_HS_",oo,sep=""),
                      paste("FCse_HS_",oo,sep=""),
                      paste("stat_HS_",oo,sep=""),
                      paste("p_HS_",oo,sep=""),
                      paste("padj_HS_",oo,sep=""))

colnames(FC_DRHS) <- c('baseMean',
                      paste("FC_DRHS_",oo,sep=""),
                      paste("FCse_DRHS_",oo,sep=""),
                      paste("stat_DRHS_",oo,sep=""),
                      paste("p_DRHS_",oo,sep=""),
                      paste("padj_DRHS_",oo,sep=""))

all.fc.dat <- cbind(all.fc.dat, FC_DRC[,2:6],FC_HSC[,2:6],FC_DRHS[,2:6])


}



```

## Get fold changes for each pair, LRT for pool and condition

```{r}

#get p values using likelihood ratio test for pool, condition, and interaction. Make an object for each so we can get the p-values later


#get fold changes for each pair of combinations. 
#Overall pool, condition
#pool in EACH condition, condition in EACH pool
#need to set up contrasts with a combined variable pool_condition
#then run DESeqDataSetFromMatrix with the combined variable INSTEAD of pool + condition (don't need to run interaction model)
#use lfcShrink to get each fold change for each combo

TTpool <- lfcShrink(TTlrt_pool_deseq, contrast =c("pool", "H","L" ), type="normal")
#H_Incu vs L_Incu
#H_RT vs L_RT
#H_Incu vs H_RT
#L_Incu vs L_RT

#step 3
#Make one data frame to hold the FCs for the combos, the  p val for pool, condition, interaction for each gene


```





